#1. Create a new GitHub Action workflow file in your repository, such as .github/workflows/push-to-scratch-org.yml
#2. Define the trigger for the workflow, such as push or pull_request , depending on your needs.
#3. Set up the Salesforce CLI by installing it in the GitHub Actions runner environment and authenticating with your Dev Hub org. You can use the
#setup-salesforce-cli action for this.
#4. Create a new scratch org using the force:org:create command. You can specify the edition, username, and other options as needed.
#5. Push the latest release from the main branch to the scratch org using the force:source:push command.
#6. Run any tests or other tasks you need to validate the deployment.
#7. Optionally, delete the scratch org using the force:org:delete command.


name: Push to Scratch Org
on:
 workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push-to-scratch-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
                 
      - name: 'Install Salesforce CLI'
         run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                  mkdir ~/sfdx
                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                  ~/sfdx/bin/sfdx version

        with:
          version: 'latest'
          auth-url: ${{ secrets.SFDX_AUTH_URL }}
      - name: Create scratch org
        run: |
          sfdx force:org:create -f config/project-scratch-def.json -s -a MyScratchOrg
      - name: Push source to scratch org
        run: |
          sfdx force:source:push
      - name: Run tests
        run: |
          sfdx force:apex:test:run
      - name: Delete scratch org
        run: |
          sfdx force:org:delete -p
